<a href="https://colab.research.google.com/github/tintubiel/MSU_ML_MFK/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.2 Градиентный спуск

В этом задании нам предстоит реализовать классический алгоритм градиентного спуска для обучения модели логистической регрессии.

Алгоритм выполнения этого задания следующий:

* На основе посчитанных в первом задании частных производных, напишем функцию подсчета градиента бинарной кросс-энтропии по параметрам модели

* Напишем функцию обновления весов по посчитанным градиентам 

* Напишем функцию тренировки модели

Замечание:
Тренировка модели проводится в несколько циклов, в рамках каждого из которых мы обновим веса модели, основываясь на предсказании для **каждого** объекта из датасета. Такие циклы называются *эпохами*. То есть одна эпоха - это набор обновлений весов, реализованный согласно посчитанным для каждого объекта из датасета ошибкам модели.

Вам необходимо реализовать обучение модели в несколько эпох. Их количество задается параметром функции. В рамках каждой эпохи необходимо пройти циклом по всем объектам обучающей выборки и обновить веса модели.

Шаблон кода для заполнения:

In [26]:
import numpy as np
# Функция подсчета градиента
def gradient(y_true: int, y_pred: float, x: np.array) -> np.array:
  """
    y_true - истинное значение ответа для объекта x
    y_pred - значение степени принадлежности объекта x классу 1, предсказанное нашей моделью
    x - вектор признакового описания данного объекта

    На выходе ожидается получить вектор частных производных H по параметрам модели, предсказавшей значение y_pred
    Обратите внимание, что размерность этого градиента должна получиться на единицу больше размерности x засчет своободного коэффициента a0
  """
  grad=np.array([])
  x=np.append(x,1)
  for i in range(len(x)):
    delta_h=x[i]*((1-y_true)*y_pred-y_true*(1-y_pred))
    grad=np.append(grad,delta_h)
  return grad


# Функция обновления весов
def update(alpha: np.array, gradient: np.array, lr: float):
  """
  alpha: текущее приближения вектора параметров модели
  gradient: посчитанный градиент по параметрам модели
  lr: learning rate, множитель перед градиентом в формуле обновления параметров
  """
  print(alpha)
  alpha_new = alpha-lr*gradient
  return alpha_new

#функция тренировки модели
def train(alpha0: np.array, x_train: np.array, y_train: np.array, lr: float, num_epoch: int):
  """
  alpha0 - начальное приближение параметров модели
  x_train - матрица объект-признак обучающей выборки
  y_train - верные ответы для обучающей выборки
  lr - learning rate, множитель перед градиентом в формуле обновления параметров
  num_epoch - количество эпох обучения, то есть полных 'проходов' через весь датасет
  """
  alpha = alpha0.copy()
  for epo in range(num_epoch):
    print(epo)
    for i,x in enumerate(x_train):
      y_pred = 1/(1 + np.exp(np.dot(alpha,np.append(x,1))))
      grad = gradient(y_train[i], y_pred, x)
      alpha = update(alpha, grad, lr)
  return alpha

In [27]:
x_train=np.array([[0,1],[2,4],[-1,2],[-3,-1]])
y_train=np.array([[0],[0],[1],[1]])
lr=0.01
num_epoch=20
alpha0=np.array([-0.5,-0.5,0])


print(train(alpha0, x_train, y_train, lr, num_epoch))

0
[-0.5 -0.5  0. ]
[-0.5        -0.50622459 -0.00622459]
[-0.51907921 -0.54438301 -0.0157642 ]
[-0.522656   -0.53722943 -0.01218741]
1
[-0.54936266 -0.54613165 -0.00328519]
[-0.54936266 -0.55247165 -0.00962519]
[-0.56866364 -0.59107362 -0.01927568]
[-0.5721325  -0.58413591 -0.01580683]
2
[-0.59936062 -0.59321196 -0.00673079]
[-0.59936062 -0.59966839 -0.01318722]
[-0.61883413 -0.63861541 -0.02292398]
[-0.6221938  -0.63189608 -0.01956431]
3
[-0.64987331 -0.64112258 -0.01033781]
[-0.64987331 -0.64769598 -0.0169112 ]
[-0.66947939 -0.68690813 -0.02671424]
[-0.67272903 -0.68040885 -0.0234646 ]
4
[-0.70079532 -0.68976428 -0.01410917]
[-0.70079532 -0.69645474 -0.02079963]
[-0.72050222 -0.73586854 -0.03065308]
[-0.72364135 -0.72959028 -0.02751395]
5
[-0.75203622 -0.73905524 -0.01804899]
[-0.75203622 -0.74586248 -0.02485624]
[-0.77181915 -0.78542835 -0.03474771]
[-0.77484761 -0.77937145 -0.03171925]
6
[-0.80351954 -0.78892876 -0.02216194]
[-0.80351954 -0.79585218 -0.02908536]
[-0.82335942 -0.835

# Замечание:

В случае, если у Вас возникли сложности с выполнением первого задания и, как следствие, у Вас не выходит сделать это, мы рекомендуем подробно ознакомиться с главой **Производные $\frac{\partial H}{\partial \omega_i}$** нашей [лекции](https://colab.research.google.com/drive/1xjX_YnXcRr8HSiYLByMHxEIAADqs7QES?usp=sharing)